#!/bin/bash

if [[ $DOCKER_TAG == *"_latest" ]] ; then
 docker tag "$IMAGE_NAME" "$DOCKER_REPO:latest"
 docker push "$DOCKER_REPO:latest"
fi

if [[ $DOCKER_TAG == *"."* ]] ; then
  docker tag "$IMAGE_NAME" "$DOCKER_REPO:${DOCKER_TAG%.*}"
  docker push "$DOCKER_REPO:${DOCKER_TAG%.*}"
fi
